
services:
  web:
    image: entry-tracker:latest
    container_name: flask-app
    environment:
      - DB_HOST=${DB_HOST}  
      - DB_USER=${DB_USER}   
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3306
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - db-data:/var/lib/mysql

networks:
  app_network:

volumes:
  db-data:
